### ISSUE TITLE
Suggested Objectives

### ISSUE THREAD

**Issue by jamiegiuliano** [learn-co-curriculum/orm-video-review-building-a-metaprogrammed-abstract-orm#12]
- How to refactor ORM to be dynamic through the use of metaprogramming and inheritance.
- Use tap to reify a raw array of data
- Set attr_accessor abstractly using a hash
- How to introspect on a hash to extract literal code and replace it with abstract code

**Comment by curiositypaths** [comment]
Hi there,

Thank you for submitting your suggested objectives.
