### ISSUE TITLE
When I play this video ..I get the following message: an error has occurred please try again later 

### ISSUE THREAD

**Issue by karuna24s** [learn-co-curriculum/orm-video-review-building-a-metaprogrammed-abstract-orm#2]
Hi!

When I play this video ..I get the following message: an error has occurred please try again later (playback id: wpdILWxf1ZREkVzk). Just wanted to report this to you. Spoke to a Learn Expert about it and he got the same error as well. The video in the Google Drive works though. 

Best,
Karuna

**Comment by AnnJohn** [comment]
thanks for catching that @karuna24s. this should be fixed now.
