### ISSUE TITLE
Suggested Summary 

### ISSUE THREAD

**Issue by JimHotchkiss** [learn-co-curriculum/orm-video-review-building-a-metaprogrammed-abstract-orm#3]
This video reviews/covers the ways to create objects and their attributes from a database using Ruby and SQL.  You will learn how to build the necessary methods  needed to extract data from a database and instantiate and save instances of a class using said data.  Additionally, you will learn how to build methods that updates a database.  These methods are built out for a specific class.  This lesson covers the logic and mechanics of abstracting each method so collectively they can be applied to any class.  

This is an excellent lesson with loads of wonderful material, ideas and insights.  It is so good that I think students would benefit by seeing it early and often.  Specifically, this video is an 1h:38m in length.  I believe, this video could easily be divided into three, virtually, stand alone videos, and each introduced to the students earlier in the sequence.  For instance, once students are introduced to 'mapping Ruby classes to database tables', the first portion of this lesson-video would be a great way to bring it all together.  The same is true for the 'Dynamic ORMs' section.  This video-lesson would be great to see just before the dynamic ORM code-along.

**Comment by gj** [comment]
Added your summary @JimHotchkiss !

I'll take a look into splitting the video up — thanks again 🙂

**Comment by lizbur10** [comment]
I agree that it would be helpful to split this video into two or three shorter videos if there's a way to do it that makes sense. 1:38 is a really long time to just sit and watch a video and it's difficult to keep absorbing information for that long.
