### ISSUE TITLE
Suggested Objectives

### ISSUE THREAD

**Issue by kyleblee** [learn-co-curriculum/orm-video-review-building-a-metaprogrammed-abstract-orm#4]
_Suggested Objectives_

- Define a class method called _.table_name_ that generates the table name for whatever class it is called on
- Understand “introspection” as it relates to dynamic programming (objects referring to themselves)
- Explain “abstract” vs. “reify” as it relates to programming
- Define a class method called _.reify_from_row_ that takes primitive data returned by the database and turns it into a literal Ruby object
- Explain object equality as it relates to reified Ruby objects created from table rows
- Define an _.update_ method to prevent duplicate data and, rather, update an existing database entry with new data
- Place private (helper) methods _.update_ and _.insert_ inside _.save_ so that the program will automatically determine which to use (based on whether or not a row already exists in the database)
- Use the double bang operator to return a boolean value of an object, instead of the object itself
- Explain the concept of “symmetry” as it relates to updating existing code
- Understand what an introspection point is and why it is important in metaprogramming
- Use an ATTRIBUTES constant hash in each class as the introspection point for that class
- Place dynamic ORM methods into their appropriate _ClassMethods_ or _InstanceMethods_ modules
- Explain when and why it is important to not use interpolation in a SQL statement (to prevent user SQL injection)
- Understand how a hook / lifecycle event / callback can be used to further abstract a dynamic ORM

**Comment by curiositypaths** [comment]
Hi there,

Thank you for submitting your suggested objectives.
