### ISSUE TITLE
Lesson placement

### ISSUE THREAD

**Issue by cboujoukos** [learn-co-curriculum/orm-video-review-building-a-metaprogrammed-abstract-orm#9]
Hello! I think this video review would be extremely helpful to view directly before doing the dynamic ORM lab.

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#9.  We will add this to our internal work queue and notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
